debug: true

database:
  host: 127.0.0.1
  username: root
  password: ''
  dbname: grendcity

gameserver: true

# Высота игрового поля
# Ставьте минимум 5, либо вообще не меняйте
hight: 50

# game:
#   name: name
#   cubes: []
#   teams: []
#   maxPlayers: 10
#   minPlayers: 10
#   center: {}
#   dmTime: 900
#   dmDur: 300
#   
  
# 20 числа ютуб
# 14 числа хостинг
