debug: true

database:
  host: 127.0.0.1
  username: root
  password: ''
  dbname: grendcity

gameserver: true

# Высота игрового поля
# минимум 5 
hight: 50

# game:
#   name: name
#   max-players: 10
#   min-players: 10
#   center: {}
#   dm-time: 900
#   dm-dur: 300
#   cubes: []
#   teams: []
 